apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dind
    type: mount
  name: dind-mount
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 132
    fsGroup: 1000
  containers:
  - image: quay.io/mauilion/dind:mount
    name: dind
    resources: {}
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
      readOnly: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
  dnsPolicy: ClusterFirst
  nodeName: lynx
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker-socket
