apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dind
    type: priv
  name: dind-priv
spec:
  containers:
  - image: quay.io/mauilion/dind:priv
    name: dind
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
