kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  disableDefaultCNI: True
nodes:
- role: control-plane
- role: worker
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "enable-admission-plugins": "PodSecurityPolicy,PodPreset"
      "runtime-config": "settings.k8s.io/v1alpha1=true"
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "10.244.0.0/16"
