apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-restrictive
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restrictive
  resources:
  - podsecuritypolicies
  verbs:
  - use
